name: Bot Cron

on:
  schedule:
    - cron: '6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mastodon-py

      - name: Run Bot
        env:
          API_SECRET: ${{ secrets.API_SECRET }}
        run: python main.py

